Updated openapi file path for documentation deployment
CraftsmenLtd/BloodConnect pull request #100
Opened 2024-09-01 10:38 UTC by mahinuzzaman

Fixes #
Updated redocly commands for the new openApi file path. 
there should be no further changes necessary. but not sure until it merges with the master. cause the deploy doc only runs on master.

- [x] Does not depend on other PRs
- [ ] Depends on other PR being merged first: #

## What kind of change does this PR introduce (check at least one)

- [ ] Bugfix
- [ ] Improvement
- [ ] New feature
- [x] Refactor
- [ ] Infrastructure
- [ ] Other (please specify)

## How would you describe the changes in a changelog (1-2 lines)?

Provide a brief overview of the changes introduced in this pull request.

## Related Issues/PRs (optional)

Link to the relevant issue(s) or provide a clear description of the problem or feature being addressed.

## How to test

- [ ] Needs regression testing (add QA needed label)

## Checklist

- [x] I have tested these changes locally and they function as expected.
- [ ] I have added or updated necessary documentation to reflect the changes.
- [ ] I have followed the project's coding style and guidelines.
- [ ] I have added appropriate test coverage to ensure the changes are functioning correctly.
- [ ] I have checked for any potential conflicts with other branches or pull requests.
- [ ] I have updated necessary OpenAPI specs

## Reviewer Request (optional)

If you have any specific requests or suggestions for reviewers, mention them here.

## Screenshots (optional)

If applicable, provide any additional screenshots or GIFs that showcase the changes made in this pull request.

## Demo Link (optional)

If applicable, provide a link to a live demo or deployment where the changes can be reviewed.

## Known Issues (optional)

If there are any known issues or limitations with the changes made in this pull request, describe them here.

## Additional Notes (optional)

Add any additional notes or comments you think are relevant to this pull request.

## Deploy risk & follow up

Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than 'No risk'.

- [x] No risk
- [ ] Low
- [ ] High

2024-09-01 17:55 UTC, melon-ruet requested changes

2024-09-01 17:55 UTC, melon-ruet commented on .github/workflows/deploy-docs.yml
> +        run: redocly bundle openapi/versions/v1.yml -o docs/openapi_combined.yaml
If redocly fails to create proper combined api speces, we will not use it

2024-09-02 09:20 UTC, melon-ruet commented on Makefile
> +	redocly bundle openapi/versions/v1.yml -o docs/openapi_combined.yaml
If you change the path, you need to fix it in docs/conf.py

```
redoc = [{
    "name": "BloodConnect API",
    "page": "openapi/api",
    "spec": f"openapi/v1/combined.yaml"
}]
```

2024-09-02 09:22 UTC, melon-ruet commented on Makefile
> +	redocly bundle openapi/versions/v1.yml -o docs/openapi_combined.yaml
Please use docs/openapi/v1.yaml

2024-09-02 09:23 UTC, melon-ruet commented on docs/conf.py
> +    "spec": f"openapi_combined.yaml"
openapi/v1.yaml

2024-09-02 09:24 UTC, melon-ruet commented on .github/workflows/deploy-docs.yml
> +        run: redocly bundle openapi/versions/v1.yml -o docs/openapi_combined.yaml
Change docs/openapi_combined.yaml to docs/openapi/v1.yaml

2024-09-02 09:30 UTC, mahinuzzaman commented on Makefile
> +	redocly bundle openapi/versions/v1.yml -o docs/openapi_combined.yaml
ok vai

2024-09-03 07:13 UTC, melon-ruet requested changes

2024-09-03 07:13 UTC, melon-ruet commented on .github/workflows/deploy-docs.yml
We need to deploy docs on openapi change. Add openapi path here

```
    paths:
      - docs/**
```

2024-09-03 07:14 UTC, mahinuzzaman commented on .github/workflows/deploy-docs.yml
> +        run: make bundle-openapi
oh. ok I'm working on it.

2024-09-03 12:59 UTC, closed without merging